### ISSUE TITLE
TypeError: createBitbucketAPI is not a function

### ISSUE THREAD

**Issue by HarisHashim** [kristianmandrup/bitbucket-api-v2#4]
I am getting

```TypeError: createBitbucketAPI is not a function```

When running in my development as well as Runkit. You can refer to the picture for the code

![image](https://user-images.githubusercontent.com/1856131/38453042-d69a5bf6-3a81-11e8-8d06-4c9a28d3a39a.png)

Thanks!
Haris

**Comment by kristianmandrup** [comment]
Yes unfortunately. Just tried upgrading to Babel but got stuck. Configuration nightmare! 

If you are unable to use ES 2015 modules, you might want to use the pre-compiled dist files:

```js
const { createBitbucketAPI } = require('bitbucket-api-v2/dist/bitbucketAPI.min')
```

**Comment by HarisHashim** [comment]
Thanks, will give it a try

**Comment by kristianmandrup** [comment]
Cool :) Please let me know if it works for you. Lib was designed to be mostly used on the backend in a node.js environment.

**Comment by nathanhinish** [comment]
I was getting this also. Looking at the source code, I just had to capitalize the second 'b' in bitbucket.

createBit**B**ucketAPI

**Comment by kristianmandrup** [comment]
Oh, sorry about that. I will fix the docs to reflect that. Thanks.
